@LogiFlow.Integration.Api_HostAddress = http://localhost:5109

GET {{LogiFlow.Integration.Api_HostAddress}}/health/live

###

GET {{LogiFlow.Integration.Api_HostAddress}}/health/ready

###

GET {{LogiFlow.Integration.Api_HostAddress}}/openapi/v1.json
